
<!DOCTYPE html>
<html lang="en">
<head>

    <title>BOOK LIST</title>
    <!-- Latest compiled and minified Bootstrap CSS -->
    <!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">console.log("hello");



    </script>

</head>
<body>

<!-- container -->
<div class="container">

    <!-- A grey horizontal navbar that becomes vertical on small screens -->
    <nav class="navbar navbar-expand-sm bg-light navbar-dark justify-content-between">
        <!--        <a class="navbar-brand" href="#">-->
        <!--            <img src="bird.jpg" alt="logo" style="width:40px;">-->
        <!--        </a>-->
        <!-- Links -->
        <ul class="navbar-nav">

        </ul>
        <form class="form-inline">
<?php //var_dump($this->bt);?>

             <?php   echo "welcome"." ";
             echo $this->bt." ";

             ?>




            <a href="<?php echo $this->url(array('controller'=>'auth',
                   'action'=>'login'));?>" class="btn btn-dark ">Login</a>
        </form>

    </nav>
    <br/>
    <br/>


    <div class='page-header'>
        <h1>BOOK LIST</h1>
    </div>




    <?php
    $this->title = "BOOKLIST";
    $this->headTitle($this->title);
    ?>

    <!--<p><a href="--><?php //echo $this->url(array('controller'=>'book',
    //        'action'=>'add'));?><!--" class="btn btn-light ">Add New Book</a></p>-->

    <table class='table  table-hover table-responsive table-condensed table-bordered table-striped'>
        <thead class="thead-dark">

        <th>Id</th>
        <th>Name</th>
        <th>Category</th>
        <th>Author</th>
        <th>Price</th>
        <th>Description</th>

        </thead>
        <?php foreach($this->books as $book) : ?>
            <tr>
                <td><?= $this->escape($book->id);?></td>
                <td><?= $this->escape($book->name);?></td>
                <td><?= $this->escape($book->category);?></td>
                <td><?= $this->escape($book->author);?></td>
                <td><?= $this->escape($book->price);?></td>
                <td><?= $this->escape($book->description);?></td>

            </tr>

        <?php endforeach; ?>
    </table>
</div>
</body></html>