<!DOCTYPE html>
<html lang="en">
<head>

    <title>BOOK LIST</title>
    <!-- Latest compiled and minified Bootstrap CSS -->
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">console.log("hello");



    </script>

</head>
<body>

<!-- container -->
<div class="container">
    <div class='page-header'>
        <h1>BOOK LIST</h1>
    </div>

    <p class="text-danger" ><h3 class="text-danger">Are you sure that you want to delete?</h3></p>
    <table class='table  table-hover  table-condensed table-bordered table-striped'>
        <thead class="thead-dark">

        <th>Id</th>
        <th>Name</th>
        <th>Category</th>
        <th>author</th>
        <th>price</th>

        </thead>
        <tr>
            <td><?=$this->book['id']?></td>
            <td><?=$this->book['name']?></td>
            <td><?=$this->book['category']?></td>
            <td><?=$this->book['author']?></td>
            <td><?=$this->book['price']?></td>
        </tr>
    </table>

<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->book['id']; ?>" />
        <input type="submit" name="del" value="Yes" class="btn btn-danger" />
        <input type="submit" name="del" value="No" class="btn "/>
    </div>
</form>
</div>
</body>
</html>