<!DOCTYPE html>
<html lang="en">
<head>

    <title>BOOK LIST</title>
    <!-- Latest compiled and minified Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script type="text/javascript">console.log("hello");



    </script>
    <style>
        input[type=text], select {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        input[type=number], select {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

    </style>

</head>
<body>

<div class="container">
    <div class='page-header'>
        <h1>BOOK LIST</h1>
    </div>


  <?php
   if($this->book1==true){?>

       <a href="<?php echo $this->url(array('controller'=>'book',
           'action'=>'index','id'=>Null));?>" class="btn btn-light "> <h4>Book List</h4></a>
       <br/>
       <br/>
   <div class="alert alert-success">
       <h3>Success! Updated.</h3>
</div>

    <?php } ?>
<div class="well">
<br /><br /><br/><br/>

<form  method="post" action="<?php echo $this->url(array('action'=>'edit')); ?>" required>
<label for="name" class="required">Name:</label>
<input type="text" name="name" id="name" value="<?=$this->book['name']?>" required>
<label for="category" >category:</label>
<input type="text" name="category" id="category" value="<?=$this->book['category']?>" required>
<label for="author" >Author:</label>
<input type="text" name="author" id="author" value="<?=$this->book['author']?>" required>
<label for="price" >Price:</label>
<input type="number" name="price" id="price" value="<?=$this->book['price']?>" required>
    <br>
    <br>
<input type="submit" class="btn  btn-primary" name="submit" id="submit" value="Add">
</form>
</div>
</div>


</body>
</html>