<!DOCTYPE html>
<html lang="en">
<head>
<title>BOOK LIST</title>
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body>
<!-- container -->
<div class="container">
    <!-- A grey horizontal navbar that becomes vertical on small screens -->
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-between">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->url(array('controller'=>'book',
                    'action'=>'add','id'=>null));?>" >Add New Book</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->url(array('controller'=>'index',
                    'action'=>'index','id'=>null));?>">Home Page</a>
            </li>
        </ul>
        <form class="form-inline nav-link" >


                <?php
                    if($this->bo)
                {
                    echo"<p class='alert alert-success  '>";
                    echo "welcome"." ".$this->boo." " ."admin"." ";
                    echo "</p>";
                }
                else
                {
                    echo "welcome".$this->boo." " ."user"." ";
                }
                ?>
            <a  href="<?php echo $this->url(array('controller'=>'auth',
                'action'=>'logout'));?>" class="btn btn-outline-success my-2 my-sm-0 ">Admin Logout</a>
        </form>

    </nav>
<br/><br/>
    <div class='page-header'>
        <h1>BOOK LIST</h1>
    </div>

<br/>

<!--<p><a href="--><?php //echo $this->url(array('controller'=>'book',
//        'action'=>'add'));?><!--" class="btn btn-light ">Add New Book</a></p>-->

<table class='table  table-hover  table-condensed table-bordered table-striped'>
    <thead class="thead-dark">
    <th></th>
        <th>Id</th>
        <th>Name</th>
        <th>Category</th>
        <th>author</th>
        <th>price</th>
        <th>Action</th>

    </thead>
    <?php foreach($this->books as $book) : ?>
        <tr>
            <td>
      <form method="post" action="<?php echo $this->url(array('action'=>'bulkreport')); ?>">
     <?php echo "<input type='checkbox' name='checkbox[]' value=' ".$book->id."'> </td>";?>
            <td><?= $this->escape($book->id);?></td>
            <td><?= $this->escape($book->name);?></td>
            <td><?= $this->escape($book->category);?></td>
            <td><?= $this->escape($book->author);?></td>
            <td><?= $this->escape($book->price);?></td>
         <td>
             <a href="<?php echo $this->url(array('controller'=>'book',
                 'action'=>'view', 'id'=>$book->id));?>" class="btn btn-secondary" >View</a>
             <a href="<?php echo $this->url(array('controller'=>'book',
                'action'=>'edit', 'id'=>$book->id));?>" class='btn btn-success left-margin'>Edit</a>
            <a href="<?php echo $this->url(array('controller'=>'book',
                'action'=>'delete', 'id'=>$book->id));?>" class="btn btn-dark delete-object">Delete</a>
             <a href="<?php echo $this->url(array('controller'=>'book',
                 'action'=>'report', 'id'=>$book->id));?>" class="btn btn-dark delete-object">Print</a>
         </td>
        </tr>

    <?php endforeach; ?>




    <br/>
    <input  type="submit" name="bulkreport" value="bulkreport"><br/>
    <input   type="submit" name="bulkdelete" value="bulkdelete">
    </form>
    <br/><br/>
</table>


</div>
</div>
</body></html>